criaCartao('Tema', 'Quem é o pai adotivo dos membros da Umbrella Academy?', 'Sir Reginald Hargreeves.');
criaCartao('Tema', 'Quantos irmãos compõem a Umbrella Academy?', 'Sete irmãos.');
criaCartao('Tema', 'Qual é o verdadeiro propósito de Reginald?', 'Criar uma máquina para resetar o universo.');
criaCartao('Tema', 'Qual é o poder secreto de Lila revelado na luta final?', 'Ela pode copiar múltiplos poderes ao mesmo tempo.');
criaCartao('Tema', 'Qual é o nome da irmã que toca violino?', 'Vanya Hargreeves.');
criaCartao('Tema', 'Qual é o poder de Número Cinco?', 'Ele pode viajar no tempo e espaço.');
criaCartao('Tema', 'Qual é o apelido de Klaus Hargreeves?', 'Número Quatro.');
criaCartao('Tema', 'Quem é o robô que atua como mãe dos irmãos?', 'Grace.');
criaCartao('Tema', 'Qual é a verdadeira identidade de Vanya?', 'O Violino Branco.');
criaCartao('Tema', 'Como Ben morreu antes dos eventos principais?', 'Em uma missão que deu errado.');
criaCartao('Tema', 'Qual é a organização que controla o tempo?', 'A Comissão.');
criaCartao('Tema', 'Quais são os nomes dos assassinos enviados pela Comissão?', 'Hazel e Cha-Cha.');
criaCartao('Tema', 'Qual é o nome do chimpanzé que trabalha para Reginald?', 'Pogo.');
criaCartao('Tema', 'Por que Número Cinco retornou ao presente?', 'Para impedir o apocalipse.');
criaCartao('Tema', 'Qual é o poder de Allison Hargreeves?', 'Manipular a realidade com suas palavras.');
criaCartao('Tema', 'O que Klaus consegue fazer com seu poder?', 'Falar com os mortos.');
criaCartao('Tema', 'Qual é o nome da esposa de Hazel?', 'Agnes.');
criaCartao('Tema', 'O que acontece com o mundo no final da primeira temporada?', 'É destruído pelo apocalipse.');
criaCartao('Tema', 'Qual é o poder de Luther Hargreeves?', 'Força sobre-humana.');
criaCartao('Tema', 'Onde Reginald envia Luther após um acidente?', 'Para a Lua.');
criaCartao('Tema', 'Qual é o segredo de Reginald revelado na terceira temporada?', 'Ele é um alienígena.');
criaCartao('Tema', 'Como Allison ativa seu poder?', 'Dizendo "Eu ouvi um boato".');
criaCartao('Tema', 'O que Klaus descobre sobre seus poderes na terceira temporada?', 'Pode se comunicar com o além e reviver.');
criaCartao('Tema', 'Quem é o personagem que trabalha na Comissão e ajuda Número Cinco?', 'Herb.');
criaCartao('Tema', 'Qual é o nome do hotel central na terceira temporada?', 'Hotel Obsidian.');
criaCartao('Tema', 'Qual é o evento apocalíptico na segunda temporada?', 'A guerra nuclear em 1963.');
criaCartao('Tema', 'O que causa o apocalipse em 2019?', 'Os poderes descontrolados de Vanya.');
criaCartao('Tema', 'Como Ben reaparece na segunda temporada?', 'Como um fantasma que segue Klaus.');
criaCartao('Tema', 'Quem é o líder da Sparrow Academy?', 'Marcus Hargreeves.');
criaCartao('Tema', 'O que é a Kugelblitz na terceira temporada?', 'Uma anomalia que consome o universo.');
criaCartao('Tema', 'Como Luther morre na terceira temporada?', 'Reginald o mata para motivar o grupo.');
criaCartao('Tema', 'Qual é a relação de Diego e Lila?', 'São amantes e têm um filho juntos.');
criaCartao('Tema', 'O que Grace faz na terceira temporada?', 'Venera a Kugelblitz como um deus.');
criaCartao('Tema', 'Quem descobre o plano secreto de Reginald na terceira temporada?', 'Allison.');
criaCartao('Tema', 'O que acontece quando o universo é reiniciado?', 'Os irmãos perdem seus poderes.');
criaCartao('Tema', 'Quem é o novo inimigo revelado no final da terceira temporada?', 'Reginald Hargreeves em sua nova realidade.');
criaCartao('Tema', 'Qual é o nome do clube secreto frequentado por Klaus?', 'Destinos Eternos.');
criaCartao('Tema', 'Quem é o diretor da Comissão na segunda temporada?', 'A Gestora.');
criaCartao('Tema', 'Qual é a habilidade especial de Lila Pitts?', 'Imitar os poderes de outros.');
criaCartao('Tema', 'Quem é Harlan Cooper?', 'Uma criança com poderes ligados a Vanya.');
criaCartao('Tema', 'Qual é a missão principal de Número Cinco na primeira temporada?', 'Evitar o apocalipse.');
criaCartao('Tema', 'Como Reginald adota os irmãos?', 'Compra de suas mães biológicas.');
criaCartao('Tema', 'Qual é o apelido de Vanya dado por seus irmãos?', 'Número Sete.');
criaCartao('Tema', 'Quem ajuda os irmãos a escapar do apocalipse em 1963?', 'Número Cinco.');
criaCartao('Tema', 'Qual é a conexão entre Vanya e Harlan?', 'Ele absorve parte de seus poderes.');
criaCartao('Tema', 'Como os irmãos retornam ao presente após os eventos de 1963?', 'Usando os poderes de Número Cinco.');
criaCartao('Tema', 'Qual é o impacto da Sparrow Academy na linha do tempo?', 'Os eventos originais são completamente alterados.');
criaCartao('Tema', 'Qual é o significado do nome "Umbrella Academy"?', 'Representa a união e proteção dos irmãos sob o mesmo "guarda-chuva" de Reginald.');
criaCartao('Tema', 'Quem compõe a banda de irmãos que aparece no trailer?', 'Os próprios atores, em um momento musical fictício.');criaCartao('Tema', 'Quem é o responsável por criar a Comissão?', 'Reginald Hargreeves.');